// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "c77bc56b-3b2f-4bc6-8ddc-2a57855c9c30");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.previous.reasons", "[\"cannot usually check for updates due to policy, testing configuration, or runtime environment\",\"app.update.langpack.enabled=true and at least one langpack is installed\",\"the maintenance service registry key is not present\"]");
user_pref("app.update.background.rolledout", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1660979059);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1660979053);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1660979038);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1660979084);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.D5BFA494011A204E", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{94d6c780-75a8-40b4-86f5-20ac40bdbd29}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1660979029);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{017af5be-3076-4278-9606-34017521a5f8}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1660979033);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1660979100488");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1660980883488");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1660979046749");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1661000646749");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220808125904");
user_pref("browser.startup.homepage_override.mstone", "103.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1660979035);
user_pref("browser.theme.content-theme", 1);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1660979039655");
user_pref("distribution.iniFile.exists.appversion", "103.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mozilla-MSIX.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "65a8a2d944424952ad2f06cc763574ab");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1660979033);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-CA@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20220808125904");
user_pref("extensions.lastAppVersion", "103.0.2");
user_pref("extensions.lastPlatformVersion", "103.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"06384374-9130-4f4b-9fab-c9fa6cdb3e2e\",\"formautofill@mozilla.org\":\"40a8e80e-2928-45ad-8493-3c861ced9224\",\"pictureinpicture@mozilla.org\":\"562fb1e7-26d8-4d5b-bf52-38e75d85ef04\",\"screenshots@mozilla.org\":\"8e565767-8eab-464b-bc52-33ad69751dff\",\"webcompat-reporter@mozilla.org\":\"2b8aabb7-1bd6-4109-bcab-9fcbc60f7786\",\"webcompat@mozilla.org\":\"b1e69373-3d34-44f9-b582-e1053f2d194c\",\"default-theme@mozilla.org\":\"6b666088-ff4d-4efb-921a-484a5149778c\",\"addons-search-detection@mozilla.com\":\"55094943-8865-4b45-9415-1773572856c3\",\"google@search.mozilla.org\":\"11c51d15-176a-42a2-acfa-776a85edc1ad\",\"wikipedia@search.mozilla.org\":\"327872d5-38ff-459d-8a5d-eef85e5570eb\",\"bing@search.mozilla.org\":\"83a3db42-0b23-403e-8888-9e66711baad0\",\"ddg@search.mozilla.org\":\"7556e948-bbb8-4e78-9998-24a1044dd46f\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1660979039);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20220808125904");
user_pref("gfx-shader-check.device-id", "0x1916");
user_pref("gfx-shader-check.driver-version", "21.20.16.4574");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("nimbus.syncdatastore.tcpByDefault", "{\"slug\":\"tcp-rollout-phase-iii-tcp-on-by-default-for-50-existing-release-profiles\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"tcpByDefault\"},\"features\":null},\"active\":true,\"enrollmentId\":\"0feaa05c-5c07-4ee4-b489-76e977e59e40\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"TCP rollout, Phase III (TCP on by default for 50% EXISTING Release profiles)\",\"userFacingDescription\":\"\\\"By default\\\" rollout: Gradually turning on Total Cookie Protection in standard browsing by default for EXISTING user profiles\",\"lastSeen\":\"2022-08-20T07:03:57.726Z\",\"featureIds\":[\"tcpByDefault\"]}");
user_pref("nimbus.syncdatastore.tcpByDefault.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x1916");
user_pref("sanity-test.driver-version", "21.20.16.4574");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20220808125904");
user_pref("security.sandbox.content.tempDirSuffix", "{0ddd20b2-d051-4db0-80f1-245feb56b4ca}");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1660979020);
user_pref("toolkit.telemetry.cachedClientID", "6cd4b399-6362-4f52-bb14-043273419721");
user_pref("toolkit.telemetry.previousBuildID", "20220808125904");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
